/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bhava.api;

import java.util.HashSet;
import java.util.Set;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/v1")
public class URLDemoApp extends Application {
	
	@Override
	public Set<Class<?>> getClasses() {
		Set<Class<?>> classes = new HashSet<Class<?>>();
		classes.add(URLDemoAppService.class);
		return classes;
	}

}
